# For x86_64 architecture only.
# You need to install magisk manager yourself.

name = "Magisk"
version = "27.0"

[[sources]]
file-name = "magisk-{version}.zip"
url = "https://github.com/topjohnwu/Magisk/releases/download/v{version}/Magisk-v{version}.apk"
checksum.sha256 = "f511bd33d3242911d05b0939f910a3133ef2ba0e0ff1e098128f9f3cd0c16610"
build.cmd = ["bsdtar", "-x", "-p", "-f", "{file_name}"]

[[contents]]
path = "{user_data}/adb/magisk"
type = "directory"

[[contents]]
path = "{user_data}/adb/magisk/busybox"
source = "{srcdir}/lib/x86_64/libbusybox.so"
type = "file"
mode = 0o755
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/magisk64"
source = "{srcdir}/lib/x86_64/libmagisk64.so"
type = "file"
mode = 0o755
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/magisk32"
source = "{srcdir}/lib/x86/libmagisk32.so"
type = "file"
mode = 0o755
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/magiskboot"
source = "{srcdir}/lib/x86_64/libmagiskboot.so"
type = "file"
mode = 0o755
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/magiskinit"
source = "{srcdir}/lib/x86_64/libmagiskinit.so"
type = "file"
mode = 0o755
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/magiskpolicy"
source = "{srcdir}/lib/x86_64/libmagiskpolicy.so"
type = "file"
mode = 0o755
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/boot_patch.sh"
source = "{srcdir}/assets/boot_patch.sh"
type = "file"
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/util_functions.sh"
source = "{srcdir}/assets/util_functions.sh"
type = "file"
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/stub.apk"
source = "{srcdir}/assets/stub.apk"
type = "file"
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/addon.d.sh"
source = "{srcdir}/assets/addon.d.sh"
type = "file"
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/loadpolicy.sh"
content = """
#!/system/bin/sh

export MAGISKTMP=/debug_ramdisk
MAKEDEV=1 $MAGISKTMP/magisk --preinit-device 2>&1
RULESCMD=""
for r in $MAGISKTMP/.magisk/preinit/*/sepolicy.rule; do
[ -f "$r" ] || continue
RULESCMD="$RULESCMD --apply $r"
done
$MAGISKTMP/magiskpolicy --live $RULESCMD 2>&1
"""
type = "file"
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/magisk"
source = "magisk64"
type = "link"

[[contents]]
path = "{user_data}/adb/magisk/su"
source = "magisk64"
type = "link"

[[contents]]
path = "{user_data}/adb/magisk/resetprop"
source = "magisk64"
type = "link"

[[contents]]
path = "{user_data}/adb/magisk/chromeos"
type = "directory"

[[contents]]
path = "{user_data}/adb/magisk/chromeos/futility"
source = "{srcdir}/assets/chromeos/futility"
type = "file"
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/chromeos/kernel_data_key.vbprivk"
source = "{srcdir}/assets/chromeos/kernel_data_key.vbprivk"
type = "file"
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{user_data}/adb/magisk/chromeos/kernel.keyblock"
source = "{srcdir}/assets/chromeos/kernel.keyblock"
type = "file"
xattr."security.selinux" = "u:object_r:magisk_file:s0"

[[contents]]
path = "{overlay}/system/etc/init/magisk.rc"
content = """
on post-fs-data
    mkdir /run/debug_ramdisk_rw 700
    mkdir /run/debug_ramdisk_work 700
    mount overlay overlay /debug_ramdisk lowerdir=/data/adb/magisk,upperdir=/run/debug_ramdisk_rw,workdir=/run/debug_ramdisk_work
    mkdir /debug_ramdisk/.magisk
    mkdir /debug_ramdisk/.magisk/mirror
    mkdir /debug_ramdisk/.magisk/preinit
    mkdir /debug_ramdisk/.magisk/block
    mkdir /debug_ramdisk/.magisk/worker
    exec u:r:magisk:s0 0 0 -- /system/bin/sh /debug_ramdisk/loadpolicy.sh
    exec u:r:magisk:s0 0 0 -- /debug_ramdisk/magisk --post-fs-data

on property:vold.decrypt=trigger_restart_framework
    exec u:r:magisk:s0 0 0 -- /debug_ramdisk/magisk --service

on nonencrypted
    exec u:r:magisk:s0 0 0 -- /debug_ramdisk/magisk --service

on property:sys.boot_completed=1
    exec u:r:magisk:s0 0 0 -- /debug_ramdisk/magisk --boot-complete

on property:init.svc.zygote=restarting
    exec u:r:magisk:s0 0 0 -- /debug_ramdisk/magisk --zygote-restart

on property:init.svc.zygote=stopped
    exec u:r:magisk:s0 0 0 -- /debug_ramdisk/magisk --zygote-restart
"""
type = "file"

[[contents]]
path = "{overlay}/vendor/etc/selinux/vendor_file_contexts"
content = """
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.atrace@1\\.0-service         u:object_r:hal_atrace_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.audio(@2\\.0-|\\.)service     u:object_r:hal_audio_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.automotive\\.audiocontrol@1\\.0-service  u:object_r:hal_audiocontrol_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.automotive\\.audiocontrol@2\\.0-service  u:object_r:hal_audiocontrol_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.automotive\\.can@1\\.0-service  u:object_r:hal_can_socketcan_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.automotive\\.evs@1\\.[0-9]-service  u:object_r:hal_evs_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.automotive\\.vehicle@2\\.0-(service|protocan-service)  u:object_r:hal_vehicle_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.bluetooth@1\\.[0-9]+-service      u:object_r:hal_bluetooth_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.bluetooth@1\\.[0-9]+-service\\.btlinux    u:object_r:hal_bluetooth_btlinux_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.biometrics\\.fingerprint@2\\.1-service u:object_r:hal_fingerprint_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.biometrics\\.face@1\\.[0-9]+-service\\.example u:object_r:hal_face_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.boot@1\\.[0-9]+-service      u:object_r:hal_bootctl_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.broadcastradio@\\d+\\.\\d+-service u:object_r:hal_broadcastradio_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.camera\\.provider@2\\.[0-9]+-service_64       u:object_r:hal_camera_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.camera\\.provider@2\\.[0-9]+-service          u:object_r:hal_camera_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.camera\\.provider@2\\.[0-9]+-service-lazy_64  u:object_r:hal_camera_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.camera\\.provider@2\\.[0-9]+-service-lazy     u:object_r:hal_camera_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.camera\\.provider@2\\.[0-9]+-external-service          u:object_r:hal_camera_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.configstore@1\\.[0-9]+-service    u:object_r:hal_configstore_default_exec:s0
/(vendor|sustem/vendor)/bin/hw/android\\.hardware\\.confirmationui@1\\.0-service u:object_r:hal_confirmationui_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.contexthub@1\\.[0-9]+-service     u:object_r:hal_contexthub_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.drm@1\\.0-service            u:object_r:hal_drm_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.drm@1\\.0-service-lazy       u:object_r:hal_drm_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.cas@1\\.[0-2]-service            u:object_r:hal_cas_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.cas@1\\.[0-2]-service-lazy       u:object_r:hal_cas_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.dumpstate@1\\.[0-1]-service\\.example      u:object_r:hal_dumpstate_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.gatekeeper@1\\.0-service     u:object_r:hal_gatekeeper_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.gnss@[0-9]\\.[0-9]-service   u:object_r:hal_gnss_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.graphics\\.allocator@2\\.0-service   u:object_r:hal_graphics_allocator_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.graphics\\.allocator@3\\.0-service   u:object_r:hal_graphics_allocator_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.graphics\\.allocator@4\\.0-service   u:object_r:hal_graphics_allocator_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.graphics\\.composer@[0-9]\\.[0-9]-service    u:object_r:hal_graphics_composer_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.health@1\\.0-service         u:object_r:hal_health_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.health@2\\.0-service         u:object_r:hal_health_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.health@2\\.1-service         u:object_r:hal_health_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.health\\.storage@1\\.0-service       u:object_r:hal_health_storage_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.identity-service.example u:object_r:hal_identity_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.input\\.classifier@1\\.0-service     u:object_r:hal_input_classifier_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.ir@1\\.0-service             u:object_r:hal_ir_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.keymaster@3\\.0-service      u:object_r:hal_keymaster_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.keymaster@4\\.0-service      u:object_r:hal_keymaster_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.keymaster@4\\.1-service      u:object_r:hal_keymaster_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.light@2\\.0-service          u:object_r:hal_light_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.light@2\\.0-service-lazy     u:object_r:hal_light_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.lights-service\\.example     u:object_r:hal_light_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.lowpan@1\\.0-service         u:object_r:hal_lowpan_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.memtrack@1\\.0-service       u:object_r:hal_memtrack_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.nfc@1\\.0-service            u:object_r:hal_nfc_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.nfc@1\\.1-service            u:object_r:hal_nfc_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.nfc@1\\.2-service            u:object_r:hal_nfc_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.media\\.omx@1\\.0-service            u:object_r:mediacodec_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.power@1\\.0-service          u:object_r:hal_power_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.power-service.example       u:object_r:hal_power_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.power\\.stats@1\\.0-service   u:object_r:hal_power_stats_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.radio\\.config@1\\.0-service  u:object_r:hal_radio_config_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.radio@1\\.2-radio-service    u:object_r:hal_radio_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.radio@1\\.2-sap-service    u:object_r:hal_radio_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.rebootescrow-service\\.default    u:object_r:hal_rebootescrow_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.sensors@[0-9]\\.[0-9]-service(\\.multihal)?  u:object_r:hal_sensors_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.secure_element@1\\.0-service u:object_r:hal_secure_element_default_exec:s0
/(vendor|system/vendor)/bin/hw/rild                                           u:object_r:rild_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.thermal@1\\.[01]-service        u:object_r:hal_thermal_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.tv\\.cec@1\\.0-service        u:object_r:hal_tv_cec_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.tv\\.input@1\\.0-service      u:object_r:hal_tv_input_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.tv\\.tuner@1\\.0-service        u:object_r:hal_tv_tuner_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.usb@1\\.0-service            u:object_r:hal_usb_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.usb\\.gadget@1\\.1-service    u:object_r:hal_usb_gadget_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.vibrator@1\\.0-service       u:object_r:hal_vibrator_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.vibrator-service.example    u:object_r:hal_vibrator_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.vr@1\\.0-service             u:object_r:hal_vr_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.wifi@1\\.0-service           u:object_r:hal_wifi_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.wifi@1\\.0-service-lazy      u:object_r:hal_wifi_default_exec:s0
/(vendor|system/vendor)/bin/hw/hostapd                                        u:object_r:hal_wifi_hostapd_default_exec:s0
/(vendor|system/vendor)/bin/hw/wpa_supplicant                                 u:object_r:hal_wifi_supplicant_default_exec:s0
/(vendor|system/vendor)/bin/vndservicemanager                                 u:object_r:vndservicemanager_exec:s0
/(vendor|system/vendor)/lib(64)?/hw/android\\.hardware\\.graphics\\.mapper@2\\.0-impl\\.so u:object_r:same_process_hal_file:s0
/(vendor|system/vendor)/lib(64)?/hw/android\\.hardware\\.graphics\\.mapper@2\\.0-impl-2\\.1\\.so u:object_r:same_process_hal_file:s0
/(vendor|system/vendor)/lib(64)?/hw/android\\.hardware\\.graphics\\.mapper@3\\.0-impl\\.so u:object_r:same_process_hal_file:s0
/(vendor|system/vendor)/lib(64)?/hw/android\\.hardware\\.graphics\\.mapper@4\\.0-impl\\.so u:object_r:same_process_hal_file:s0
/(vendor|system/vendor)/lib(64)?/hw/android\\.hardware\\.renderscript@1\\.0-impl\\.so     u:object_r:same_process_hal_file:s0
/(vendor|system/vendor)/lib(64)?/hw/gralloc\\.default\\.so                              u:object_r:same_process_hal_file:s0
/(vendor|system/vendor)/lib(64)?/libhwbinder.so u:object_r:same_process_hal_file:s0
/(vendor|system/vendor)/lib(64)?/libhidltransport.so u:object_r:same_process_hal_file:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.biometrics\\.fingerprint@2\\.0-service u:object_r:hal_fingerprint_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.gnss@1\\.0-service\\.legacy u:object_r:hal_gnss_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.light@2\\.0-service\\.aw2013 u:object_r:hal_light_default_exec:s0
/(vendor|system/vendor)/bin/hw/vendor\\.lineage\\.livedisplay@2\\.0-service-sysfs    u:object_r:hal_lineage_livedisplay_sysfs_exec:s0
/(vendor|system/vendor)/bin/hw/vendor\\.lineage\\.trust@1\\.0-service u:object_r:hal_lineage_trust_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.usb@1\\.0-service\\.basic u:object_r:hal_usb_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.usb@1\\.1-service\\.typec u:object_r:hal_usb_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.vibrator@1\\.0-service\\.lineage u:object_r:hal_vibrator_default_exec:s0
/(vendor|system/vendor)/bin/hw/android\\.hardware\\.wifi@1\\.0-service\\.legacy u:object_r:hal_wifi_default_exec:s0
/data/vendor/wifi/wpa(/.*)?                                                   u:object_r:wpa_data_file:s0
/data/vendor/wifi/hostapd(/.*)?                                               u:object_r:hostapd_data_file:s0
/debug_ramdisk(/.*)?                                                          u:object_r:magisk_file:s0
/data/adb/magisk(/.*)?                                                        u:object_r:magisk_file:s0
"""
type = "file"
